[workspace]
members = [
  "plugins/*",
  "plugins/*/tests/*",
  "plugins/*/examples/*/src-tauri",
  "examples/*/src-tauri",
]
resolver = "2"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
log = "0.4"
tauri = "2.0.0-beta.1"
tauri-build = "2.0.0-beta.0"
tauri-plugin = "2.0.0-beta.0"
serde_json = "1"
thiserror = "1"
url = "2"
schemars = "0.8"

[workspace.package]
edition = "2021"
authors = ["Tauri Programme within The Commons Conservancy"]
license = "Apache-2.0 OR MIT"
rust-version = "1.70"

# default to small, optimized release binaries
[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "s"

[patch.crates-io]
swift-rs = { git = "https://github.com/guillemcordoba/swift-rs", branch = "main" }
tao = { git = "https://github.com/guillemcordoba/tao", branch = "dev" }
